### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by RafaelBlueLobster** [kimai/user-bundle#1]
Hi!

I'm not sure if the instructions for installning user-bundle are posted here, but i cant just figure out how to do it. I zipped all the files into my server but then i dont really know what to do.

Thanks in advance
/Rafael

**Comment by kevinpapst** [comment]
Why exactly would you want to install it?

**Comment by RafaelBlueLobster** [comment]
Hi kevin, 

Well, is it enough to just unzip the files into the same directory as in Kimai and then the bundle will do its job? 

/Rafael

**Comment by kevinpapst** [comment]
This bundle is not meant to be used manually. 
It is a core feature of Kimai and provides internal features.
You cannot install it manually.
Just forget that it exists.
